### PR TITLE
Flush pending element definitions in `define`-call order before document order.

### PR DESCRIPTION
**Pull request by bicknellr**

### CODE REVIEW

**Comment by bicknellr** [comment]
cc @frankiefu, for some reason it won't let me add you as a reviewer.

**Comment by samuelli** [comment]
LGTM from me, but I don't know enough here. Deferring to @sorvell.

**Comment by bicknellr** [comment]
cc @azakus, @sorvell asked me to include you as a reviewer.

**Comment by samuelli** [comment]
@azakus: can you build & release webcomponentsjs please?

**Comment by azakus** [comment]
@samuelli I did so yesterday with wc 1.0.5

**Comment by samuelli** [comment]
@azakus: oh, awesome thanks.

Why does GitHub show it not as the latest release?

image

**Comment by azakus** [comment]
That bit is a manual process, but as simple as a button click. Which I'll do now.

**Pull request merged**
