### PR TITLE
Add tests for `Node.textContent`

### LINKED ISSUE #115: `Node.prototype.textContent` does not have tests.
https://github.com/search?q=textContent+path%3A%2Ftests%2Fhtml+repo%3Awebcomponents%2Fcustom-elements&type=Code

### PR DESCRIPTION
**Pull request by TimvdLippe**
Used the tests originally created by @limonte in #130 as well as a copy of the disconnect tests from `innerHTML`.

Fixes #115

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Again Safari 9 breaking :cry:

**Comment by bicknellr** [comment]
Looks like there is a bug Safari 9 where setting `textContent` to `""` actually causes the node's child nodes to be replaced with a single text node with text `""`, rather than just removing all the child nodes:
```javascript
div = document.createElement('div');
div.childNodes.length === 0; // true everywhere
div.textContent = "";
div.childNodes.length; // 1 in Safari 9, 0 everywhere else
```
I'd say change the values that you're setting to `textContent` to something other than the empty string; then, you can assert `div.childNodes.length === 1` after setting `textContent` in all cases.

**Comment by TimvdLippe** [comment]
That fixed it, awesome thanks for the investigation @bicknellr !

**Comment by TimvdLippe** [comment]
@bicknellr Done :+1:

**Pull request merged**
