### PR TITLE
call attrChangedCb even if value hasn't changed

### PR DESCRIPTION
**Pull request by cronon**
Spec says to call it even when the value hasn't changed.
https://www.w3.org/TR/custom-elements/#concept-element-attributes-change
https://bugs.chromium.org/p/chromium/issues/detail?id=676247

resolves https://github.com/webcomponents/custom-elements/issues/85

### CODE REVIEW

**Comment by bicknellr** [comment]
Hi @cronon, thanks for submitting this! It looks like you need to [sign the CLA](https://cla.developers.google.com).

**Comment by cronon** [comment]
Hi @bicknellr, I thought I've already signed it. How can I check it?

**Comment by bicknellr** [comment]
I think if you click the button at the bottom of the page ("Manage your agreements") it should show you which agreements you've signed, if any.

**Comment by cronon** [comment]
Yes, there is agreement signed. So, how do you check whether contributors have it?

**Comment by bicknellr** [comment]
Found it, thanks! We've got a tool that lets us look up people by their github username / email to check if they've signed it; I'm not sure if it's accessible externally though.

**Comment by bicknellr** [comment]
One more thing, should this change also be made to `setAttributeNS` (directly below)?

**Comment by cronon** [comment]
Right, I forgot this method even exists :)

**Pull request merged**
