### PR TITLE
Allow ES6 classes through native-shim.js

### LINKED ISSUE #142: Native ES6 classes do not work when the native-shim is in use.
Currently if the native shim is in use, only es5 custom elements can be used.

**Console Output:**
`Uncaught TypeError: Class constructor MyElement cannot be invoked without 'new'`

### PR DESCRIPTION
**Pull request by grimly**
Fixes #142.

I only have Chrome and IE 11 available to run the tests, I completed them to make sure any issue is raised ASAP.

Reworked the native-shim.js to have a valid syntax for IE11 (one can only copy this shim and have no penalty on IE 11)

### CODE REVIEW

**Comment by RebeccaStevens** [comment]
Closes #143

**Comment by bicknellr** [comment]
@justinfagnani is the most knowledgeable about the native shim, so I think he would really be the best reviewer here. If I remember correctly, the native shim specifically avoids `eval` (which both this PR and #143 use) so that it can be used with CSP types that block it.

**Comment by justinfagnani** [comment]
Avoiding Reflect.construct is the main point of the shim being structured the way it is. At the time we measured, Reflect.construct was 20-30x slower than native super calls. If Reflect.construct has gotten faster enough since then to be viable, then I think that relying on the new Babel transform that allows extending built-in classes is a better options, since it eliminates the need for the shim altogether.

Also, we need to avoid eval(), which isn't CSP compliant.

**Comment by grimly** [comment]
The shim actually breaks any web component that respect the actual specs, this is the main issue raised by #142.
If one component inserts it because he needs it, fine. It goes wrong when it breaks all other components. 

`Reflect.construct` is roughly 30% slower from my observations (Chrome 64).

I dropped the `eval()` and let `this.constructor` be the only option. This is not ideal but this is the best we have if we can't allow syntax errors.

**Pull request merged**
